- job:
    name: congress-tempest-base
    parent: devstack-tempest
    description: |
      Congress devstack tempest tests job
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^congress/tests/.*$
      - ^releasenotes/.*$
    required-projects:
      - name: openstack/devstack-gate
      - name: openstack/aodh
      - name: openstack/python-aodhclient
      - name: openstack/congress
      - name: openstack/congress-dashboard
      - name: openstack/congress-tempest-plugin
      - name: openstack/python-congressclient
      - name: openstack/murano
      - name: openstack/murano-dashboard
      - name: openstack/python-muranoclient
      - name: openstack/mistral
      - name: openstack/python-mistralclient
      - name: openstack/heat
      - name: openstack/python-heatclient
      - name: openstack/monasca-agent
      - name: openstack/monasca-api
      - name: openstack/monasca-common
      - name: openstack/monasca-grafana-datasource
      - name: openstack/monasca-notification
      - name: openstack/monasca-persister
      - name: openstack/monasca-statsd
      - name: openstack/monasca-thresh
      - name: openstack/monasca-ui
      - name: openstack/python-monascaclient
    timeout: 6000
    vars:
      devstack_plugins:
        congress: https://opendev.org/openstack/congress
        heat: https://opendev.org/openstack/heat
        murano: https://opendev.org/openstack/murano
        neutron: https://opendev.org/openstack/neutron
      devstack_services:
        tempest: true
        neutron-qos: true
        horizon: false
        # swift disabled for py3
        s-proxy: false
        s-object: false
        s-container: false
        s-account: false
        c-bak: false  # requires swift
      tempest_concurrency: 1
      tox_envlist: all
      tempest_test_regex: congress_tempest_plugin.*
      devstack_localrc:
        LIBS_FROM_GIT: python-congressclient
        SERVICE_TIMEOUT: 120  # default too short for this job
        TEMPEST_PLUGINS: '"/opt/stack/congress-tempest-plugin"'
        CONGRESS_MULTIPROCESS_DEPLOYMENT: true
        CONGRESS_EXPOSE_ENCRYPTION_KEY_FOR_TEST: true
        ENABLE_CONGRESS_Z3: true
        USE_Z3_RELEASE: 4.7.1

- job:
    name: congress-tempest-py2
    parent: congress-tempest-base
    vars:
      devstack_plugins:
        aodh: https://opendev.org/openstack/aodh
        mistral: https://opendev.org/openstack/mistral
        monasca-api: https://opendev.org/openstack/monasca-api
      devstack_services:
        s-proxy: true
        s-object: true
        s-container: true
        s-account: true
        c-bak: true

- job:
    name: congress-tempest-py3
    parent: congress-tempest-base
    vars:
      devstack_localrc:
        USE_PYTHON3: true

- job:
    name: congress-tempest-replicated
    parent: congress-tempest-base
    voting: false
    vars:
      devstack_localrc:
        CONGRESS_REPLICATED: true

- job:
    name: congress-tempest-replicated-mysql
    parent: congress-tempest-replicated
    vars:
      database: mysql

- job:
    name: congress-tempest-replicated-postgresql
    parent: congress-tempest-replicated
    voting: false
    vars:
      devstack_services:
        mysql: false
        postgresql: true

- job:
    name: congress-tempest-py2-mysql
    parent: congress-tempest-py2
    vars:
      database: mysql

- job:
    name: congress-tempest-py3-mysql
    parent: congress-tempest-py3
    vars:
      database: mysql

- job:
    name: congress-tempest-py2-JsonIngester
    parent: congress-tempest-base
    voting: false
    vars:
      devstack_localrc:
        ENABLE_CONGRESS_JSON: true

- job:
    name: congress-tempest-py3-JsonIngester
    parent: congress-tempest-py2-JsonIngester
    voting: false
    vars:
      devstack_localrc:
        USE_PYTHON3: true

- job:
    name: congress-tempest-py2-postgresql
    parent: congress-tempest-base
    voting: false
    vars:
      devstack_services:
        mysql: false
        postgresql: true

- job:
    name: congress-tempest-py3-postgresql
    parent: congress-tempest-py2-postgresql
    voting: false
    vars:
      devstack_localrc:
        USE_PYTHON3: true

- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - release-notes-jobs-python3
      - publish-openstack-docs-pti
      - periodic-stable-jobs
    check:
      jobs:
        - congress-tempest-py2-mysql
        - congress-tempest-py3-mysql
        - congress-tempest-replicated-postgresql
        - congress-tempest-py2-JsonIngester
        - congress-tempest-py3-JsonIngester
        # Note: the above jobs most likely provides sufficient coverage
        # - congress-tempest-py2-postgresql
        # - congress-tempest-py3-postgresql
        # - congress-tempest-replicated-mysql

        # TripleO jobs that deploy Congress.
        # Note we don't use a project-template here, so it's easier
        # to disable voting on one specific job if things go wrong.
        # tripleo-ci-centos-7-scenario001-multinode-oooq will only
        # run on stable/pike while the -container will run in Queens
        # and beyond.
        # If you need any support to debug these jobs in case of
        # failures, please reach us on #tripleo IRC channel.
# temporarily disable tripleO check until faster single-node job is available
#        - tripleo-ci-centos-7-scenario007-multinode-oooq-container:
#            voting: false
    gate:
      queue: congress
      jobs:
        - congress-tempest-py2-mysql
        - congress-tempest-py3-mysql
