- hosts: all
  name: Autoconverted job legacy-congress-dsvm-py35-api-mysql from old job gate-congress-dsvm-py35-api-mysql-ubuntu-xenial-nv
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack-infra/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              git://git.openstack.org \
              openstack-infra/devstack-gate
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          cat << 'EOF' >>"/tmp/dg-local.conf"
          [[local|localrc]]
          # swift is not ready for python3 yet
          disable_service s-account
          disable_service s-container
          disable_service s-object
          disable_service s-proxy
          # without Swift, c-bak cannot run (in the Gate at least)
          disable_service c-bak
          # aodh not ready for python3 yet
          # enable_plugin aodh git://git.openstack.org/openstack/aodh
          enable_plugin heat git://git.openstack.org/openstack/heat
          enable_plugin congress git://git.openstack.org/openstack/congress
          enable_plugin murano git://git.openstack.org/openstack/murano
          enable_plugin neutron https://git.openstack.org/openstack/neutron
          # To deploy congress as multi-process (api, pe, datasources)
          CONGRESS_MULTIPROCESS_DEPLOYMENT=True
          CONGRESS_EXPOSE_ENCRYPTION_KEY_FOR_TEST=True
          LIBS_FROM_GIT=python-congressclient
          ENABLE_CONGRESS_Z3=True
          USE_Z3_RELEASE=4.7.1
          TEMPEST_PLUGINS='/opt/stack/new/congress-tempest-plugin /opt/stack/new/murano-tempest-plugin /opt/stack/new/heat-tempest-plugin'
          EOF
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          export DEVSTACK_GATE_USE_PYTHON3=True
          # swift is not ready for python3 yet
          # ENABLED_SERVICES=s-proxy,s-object,s-container,s-account,
          ENABLED_SERVICES+=neutron-qos
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_REGEX="congress_tempest_plugin"
          export DEVSTACK_GATE_NEUTRON=1
          export PROJECTS="openstack/congress $PROJECTS"
          export PROJECTS="openstack/congress-dashboard $PROJECTS"
          export PROJECTS="openstack/python-congressclient $PROJECTS"
          export PROJECTS="openstack/congress-tempest-plugin $PROJECTS"
          export PROJECTS="openstack/murano $PROJECTS"
          export PROJECTS="openstack/murano-dashboard $PROJECTS"
          export PROJECTS="openstack/python-muranoclient $PROJECTS"
          export PROJECTS="openstack/murano-tempest-plugin $PROJECTS"
          export PROJECTS="openstack/heat-tempest-plugin $PROJECTS"

          export ENABLED_SERVICES
          export BRANCH_OVERRIDE=default
          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
