- hosts: all
  name: Congress pe-replicated base
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              https://opendev.org \
              openstack/devstack-gate
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          cat << 'EOF' >>"/tmp/dg-local.conf"
          [[local|localrc]]
          enable_plugin ceilometer https://opendev.org/openstack/ceilometer
          enable_plugin heat https://opendev.org/openstack/heat
          enable_plugin congress https://opendev.org/openstack/congress
          enable_plugin murano https://opendev.org/openstack/murano
          enable_plugin aodh https://opendev.org/openstack/aodh
          enable_plugin designate https://opendev.org/openstack/designate
          enable_plugin neutron https://opendev.org/openstack/neutron
          CONGRESS_REPLICATED=True
          # To deploy congress as multi-process (api, pe, datasources)
          CONGRESS_MULTIPROCESS_DEPLOYMENT=True
          CONGRESS_EXPOSE_ENCRYPTION_KEY_FOR_TEST=True

          EOF
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          ENABLED_SERVICES=s-proxy,s-object,s-container,s-account,
          ENABLED_SERVICES+=h-eng,h-api,h-api-cfn,h-api-cw,
          ENABLED_SERVICES+=q-qos

          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_ALL_PLUGINS=1
          export DEVSTACK_GATE_TEMPEST_REGEX="congress_tempest_tests"
          export DEVSTACK_GATE_NEUTRON=1
          export PROJECTS="openstack/congress $PROJECTS"
          export PROJECTS="openstack/congress-dashboard $PROJECTS"
          export DEVSTACK_PROJECT_FROM_GIT=python-congressclient
          export PROJECTS="openstack/murano $PROJECTS"
          export PROJECTS="openstack/aodh $PROJECTS"
          export PROJECTS="openstack/murano-dashboard $PROJECTS"
          export PROJECTS="openstack/python-muranoclient $PROJECTS"
          export PROJECTS="openstack/python-aodhclient $PROJECTS"
          export PROJECTS="openstack/designate $PROJECTS"
          export PROJECTS="openstack/designate-tempest-plugin $PROJECTS"

          export ENABLED_SERVICES
          export BRANCH_OVERRIDE=default
          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi
          if [ "{{ database }}" == "postgresql" ] ; then
              export DEVSTACK_GATE_POSTGRES=1
          fi

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
