#!/bin/sh
# Copyright (c) 2013 VMware, Inc. All rights reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#


SRCSCRIPT=`readlink -f $0`
SCRIPTDIR=`dirname $SRCSCRIPT`
ROOTDIR=`dirname $SCRIPTDIR`
PYSRCDIR=$ROOTDIR/congress
SERVERDIR=$PYSRCDIR/server
THIRDPARTYDIR=$ROOTDIR/thirdparty

export PYTHONPATH=$PYSRCDIR:$THIRDPARTYDIR:$ROOTDIR

ARGS="$@"
cd $SERVERDIR
python congress_server.py $ARGS
