#!/bin/sh
# Copyright (c) 2013 VMware, Inc. All rights reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

# Usage:  run_tests

# TODO(pjb): Run from a build (rather than source) dir
SRCSCRIPT=`readlink -f $0`
SCRIPTDIR=`dirname $SRCSCRIPT`
ROOTDIR=`dirname $SCRIPTDIR`

SRCDIR=$ROOTDIR/congress
THIRDPARTYDIR=$ROOTDIR/thirdparty
TESTDIR=$ROOTDIR/congress/tests
export PYTHONPATH=$SRCDIR:$THIRDPARTYDIR:$SRCDIR/policy

# Use nosetests to find all unitests in tree
ARGS="$@"
cd $ROOTDIR
nosetests $ARGS

cd $ROOTDIR/congress/tests
nosetests functional/test_api.py

